# Generated by Django 3.1.6 on 2021-03-24 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_author_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitems',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
